version: '3.9'

services:
  user_app:
    container_name: user_app
    image: java_user_app
    build: .
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=jdbc:postgresql://user_db:5432/users_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - user_db

  user_db:
    container_name: user_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
